words = [
    "basecoat",
    "bitmaprenderer",
    "bprogress",
    "bundler",
    "cmyk",
    "dragover",
    "ggg",
    "gridify",
    "gzip",
    "luma",
    "minmax",
    "noopener",
    "onchange",
    "ondragover",
    "ondrop",
    "onsubmit",
    "pico",
    "prerender",
    "rollup",
    "rrr",
    "runed",
    "srgb",
    "steinberg",
    "sveltejs",
    "sveltekit",
    "unplugin",
    "vite",
    "wplace",
    "zod",
]
